# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Country.create(name:'Österreich',alpha2_code:'AT')
Country.create(name:'Zypern',alpha2_code:'CY')
Country.create(name:'Weißrussland',alpha2_code:'BY')
Country.create(name:'Vereinigtes Königreich',alpha2_code:'GB')
Country.create(name:'Vatikanstadt',alpha2_code:'VA')
Country.create(name:'Ungarn',alpha2_code:'HU')
Country.create(name:'Ukraine',alpha2_code:'UA')
Country.create(name:'Türkei',alpha2_code:'TR')
Country.create(name:'Tschechien',alpha2_code:'CZ')
Country.create(name:'Spanien',alpha2_code:'ES')
Country.create(name:'Slowenien',alpha2_code:'SI')
Country.create(name:'Slowakei',alpha2_code:'SK')
Country.create(name:'Serbien',alpha2_code:'RS')
Country.create(name:'Schweiz',alpha2_code:'CH')
Country.create(name:'Schweden',alpha2_code:'SE')
Country.create(name:'San Marino',alpha2_code:'SM')
Country.create(name:'Russland',alpha2_code:'RU')
Country.create(name:'Rumänien',alpha2_code:'RO')
Country.create(name:'Portugal',alpha2_code:'PT')
Country.create(name:'Polen',alpha2_code:'PL')
Country.create(name:'Norwegen',alpha2_code:'NO')
Country.create(name:'Niederlande',alpha2_code:'NL')
Country.create(name:'Montenegro',alpha2_code:'ME')
Country.create(name:'Monaco',alpha2_code:'MC')
Country.create(name:'Moldawien',alpha2_code:'MD')
Country.create(name:'Mazedonien',alpha2_code:'MK')
Country.create(name:'Malta',alpha2_code:'MT')
Country.create(name:'Luxemburg',alpha2_code:'LU')
Country.create(name:'Litauen',alpha2_code:'LT')
Country.create(name:'Liechtenstein',alpha2_code:'LI')
Country.create(name:'Lettland',alpha2_code:'LV')
Country.create(name:'Kroatien',alpha2_code:'HR')
Country.create(name:'Kasachstan',alpha2_code:'KZ')
Country.create(name:'Italien',alpha2_code:'IT')
Country.create(name:'Island',alpha2_code:'IS')
Country.create(name:'Irland',alpha2_code:'IE')
Country.create(name:'Griechenland',alpha2_code:'GR')
Country.create(name:'Frankreich',alpha2_code:'FR')
Country.create(name:'Finnland',alpha2_code:'FI')
Country.create(name:'Estland',alpha2_code:'EE')
Country.create(name:'Dänemark',alpha2_code:'DK')
Country.create(name:'Deutschland',alpha2_code:'DE')
Country.create(name:'Bulgarien',alpha2_code:'BG')
Country.create(name:'Bosnien/Herzegowina',alpha2_code:'BA')
Country.create(name:'Belgien',alpha2_code:'BE')
Country.create(name:'Andorra',alpha2_code:'AD')
Country.create(name:'Albanien',alpha2_code:'AL')
